name: Manual Release (Electron)

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version (e.g., 1.0.7)"
        required: true
      publish_tag:
        description: "Create and push tag v<version>"
        required: true
        type: boolean
        default: true

permissions:
  contents: write

jobs:
  win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Bump version in electron/package.json
        shell: bash
        run: |
          node -e "const fs=require('fs');const p='electron/package.json';const j=JSON.parse(fs.readFileSync(p));j.version='${{ inputs.version }}';fs.writeFileSync(p, JSON.stringify(j,null,2));"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add electron/package.json
          git commit -m "ci: bump version to v${{ inputs.version }}" || echo "no changes"

      - name: Create and push tag (optional)
        if: ${{ inputs.publish_tag == 'true' }}
        shell: bash
        run: |
          git tag v${{ inputs.version }} || echo "tag exists"
          git push origin HEAD
          git push origin v${{ inputs.version }} || echo "tag push skipped"

      - name: Install deps
        working-directory: electron
        shell: pwsh
        run: |
          if (Test-Path package-lock.json) { npm ci } else { npm install }

      - name: Build & Publish (Windows)
        working-directory: electron
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run ci:build
